version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=${DB_TIMEZONE}
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    environment:
      - TZ=${DB_TIMEZONE}
    restart: always
    ports:
      - 6379:6379

  beat:
    build: .
    volumes:
      - ./src:/web/src
    environment:
      - TZ=${DB_TIMEZONE}
    command:
      - sh
      - -c
      - |
        cd src && poetry run celery --app=celdery.celery beat --loglevel=INFO
    depends_on:
      - redis
      - web

  worker:
    build: .
    volumes:
      - ./src:/web/src
    environment:
      - TZ=${DB_TIMEZONE}
    command:
      - sh
      - -c
      - |
        cd src && poetry run celery --app=celdery.celery worker --loglevel=INFO
    depends_on:
      - redis
      - web

  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    stop_signal: SIGINT
    depends_on:
      - db
    volumes:
      - ./src:/web/src
      - ./migration:/web/migration
    environment:
      - DOCKER_CONTAINER=true
      - TZ=${DB_TIMEZONE}
    command:
      - sh
      - -c
      - |
        poetry run alembic upgrade head && poetry run python ./src/wsgi.py
