version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=${DB_TIMEZONE}
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./src:/web/src
      - .env:/web/.env
    environment:
      - DOCKER_CONTAINER=true
      - TZ=${DB_TIMEZONE}
    command: poetry run python /web/src/wsgi.py
